all:
  vars:
    sib_server: 192.168.1.196
    ansible_user: matija
    ansible_become: true

fleet:
  hosts:
    debian-dockerhost:
      ansible_host: 192.168.1.25
      host_labels:
        environment: production
        role: docker-host
    docker-server:
      ansible_host: 192.168.1.200
      host_labels:
        environment: production
        role: docker-server
