all:
  vars:
    sib_server: 192.168.1.163
    ansible_user: root

fleet:
  hosts:
    nodocker-fleet:
      ansible_host: 192.168.1.164
      host_labels:
        environment: test
        docker: "false"
    docker-fleet:
      ansible_host: 192.168.1.165
      host_labels:
        environment: test
        docker: "true"
    vm-fleet:
      ansible_host: 192.168.1.31
      ansible_user: matija
      ansible_become: true
      host_labels:
        environment: test
        type: vm
